name: Elixir CI

env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: astro_test
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: '1.14.3'
        otp-version: '24'

    - name: Restore dependencies cache
      uses: actions/cache@v2
      id: mix-cache
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Restore build cache
      uses: actions/cache@v2
      id: build-cache
      with:
        path: _build
        key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-build-

    - name: Install dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Compile Dependencies
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: MIX_ENV=test mix compile

    - name: Run tests
      run: mix test

    # - name: Code Quality
    #   run: mix code_quality

    - name: Ensure formatted
      run: mix format --check-formatted